<a href="https://colab.research.google.com/github/rubel-ds-ai/sm-tasks/blob/main/Assignment_3_NumPy_and_Pandas_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Student Performance Dataset Analysis
Dataset Information
Student Performance Dataset (StudentsPerformance.csv)

1000 students with academic performance data
8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score
Score Range: 0-100 for each subject
Demographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none
"""

In [4]:
#Task 1.1: Data Loading and Exploration
import numpy as np
import pandas as pd

from google.colab import drive
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Load CSV
file_path = '/content/drive/My Drive/DataSets/sm-datasets/StudentsPerformance.csv'

# Load the dataset
df = pd.read_csv(file_path)

# Your tasks:
# 1. Display first 10 rows
# 2. Show dataset shape and info()
# 3. Display unique values in each categorical column
# 4. Show basic statistics for all score columns

# Your code here:

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

(1000, 8)

In [11]:
# 1. Display first 10 rows
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [17]:
# 2. Show dataset shape and info()
print(f"Shape of the DataSet is: {df.shape}\n")

print(df.info())

Shape of the DataSet is: (1000, 8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [24]:
# 3. Display unique values in each categorical column
# df.apply(lambda x: x.unique())
unique_values = df.apply(lambda x: x.unique())
print(unique_values)

gender                                                            [female, male]
race/ethnicity                     [group B, group C, group A, group D, group E]
parental level of education    [bachelor's degree, some college, master's deg...
lunch                                                   [standard, free/reduced]
test preparation course                                        [none, completed]
math score                     [72, 69, 90, 47, 76, 71, 88, 40, 64, 38, 58, 6...
reading score                  [72, 90, 95, 57, 78, 83, 43, 64, 60, 54, 52, 8...
writing score                  [74, 88, 93, 44, 75, 78, 92, 39, 67, 50, 52, 4...
dtype: object

In [26]:
# 3. Display unique values in each categorical column - alternative

for col in df.select_dtypes(include=['object', 'category']).columns:
    print(f"Unique values in '{col}': {df[col].unique()}\n")

Unique values in 'gender': ['female' 'male']

Unique values in 'race/ethnicity': ['group B' 'group C' 'group A' 'group D' 'group E']

Unique values in 'parental level of education': ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

Unique values in 'lunch': ['standard' 'free/reduced']

Unique values in 'test preparation course': ['none' 'completed']

In [25]:
# 4. Show basic statistics for all score columns
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
#Task 1.2: NumPy Array Operations
# Convert score columns to numpy arrays
math_scores = df['math score'].values
reading_scores = df['reading score'].values
writing_scores = df['writing score'].values

# Your tasks:
# 1. Calculate mean, median, std, min, max for each subject using NumPy
# 2. Find total students who scored above 80 in math
# 3. Find total students who scored below 50 in any subject
# 4. Calculate the overall average score across all three subjects

# Expected output example:
# Math - Mean: 66.1, Median: 66.0, Std: 15.2
# Students with math > 80: 132
# Students with any score < 50: 178

# Your code here:

In [ ]:
# Task 2.1: Identify and Handle Missing Data
# Check the dataset for any missing values
# Your tasks:
# 1. Check for null values in each column using .isnull().sum()
# 2. Check for any impossible values (scores > 100 or < 0)
# 3. Display summary of data quality

# Note: This dataset is clean, but let's verify!

# Your code here:

In [ ]:
#Task 2.2: Create and Fix Missing Value
# Artificially create missing data for practice
import numpy as np

# Your tasks:
# 1. Make a copy of the dataset: df_practice = df.copy()
# 2. Randomly set 50 math scores to np.nan
# 3. Randomly set 30 writing scores to np.nan
# 4. Fill missing math scores with the MEDIAN math score
# 5. Fill missing writing scores with the MEAN writing score
# 6. Verify no missing values remain

# Steps to follow:
# Step 1: Create copy and show original missing values
df_practice = df.copy()
print("Original missing values:", df_practice.isnull().sum())

# Step 2: Create missing data
np.random.seed(42)  # For reproducible results
missing_math_idx = np.random.choice(df_practice.index, 50, replace=False)
missing_writing_idx = np.random.choice(df_practice.index, 30, replace=False)

# Continue the task...
# Your code here:

In [ ]:
#Task 3.1:Answer Simple Questions About Student Performance
# Your tasks:
# 1. Display first 5 rows using .head()
# 2. Display last 5 rows using .tail()
# 3. Show dataset shape using .shape
# 4. Show column names using .columns
# 5. Show data types using .dtypes
# 6. Show basic info using .info()

# Your code here:

In [ ]:
#Task 3.2: Basic Groupby Analysis
# Comprehensive groupby analysis
# Your tasks:

# 1. Group by 'gender' and calculate:
#    - Average scores in all subjects
#    - Count of students

# 2. Group by 'test preparation course' and show:
#    - Mean scores for each subject
#    - Show which subject benefits most from test prep

# 3. Group by 'parental level of education' and calculate:
#    - Average math score for each education level
#    - Rank education levels by math performance

# 4. Group by 'lunch' type and show:
#    - Average scores for each subject
#    - Count of students in each lunch category

# Your code here:

In [ ]:
#Task 3.3: Use your data analysis skills to answer these easy questions:

# 1. Who performs better in math - males or females?
#    - Calculate average math score by gender
#    - Show the difference between male and female average

# 2. Which subject do students perform best in overall?
#    - Calculate the overall average for math, reading, and writing
#    - Rank the subjects from highest to lowest average score

# 3. What's the impact of parental education?
#    - Find the average total score for each parental education level
#    - Identify which education level leads to highest student performance