<a href="https://colab.research.google.com/github/rubel-ds-ai/sm-tasks/blob/main/Assignment_3_NumPy_and_Pandas_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Student Performance Dataset Analysis
Dataset Information
Student Performance Dataset (StudentsPerformance.csv)

1000 students with academic performance data
8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score
Score Range: 0-100 for each subject
Demographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none
"""

'\nStudent Performance Dataset Analysis\nDataset Information\nStudent Performance Dataset (StudentsPerformance.csv)\n\n1000 students with academic performance data\n8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score\nScore Range: 0-100 for each subject\nDemographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none\n'

In [ ]:
#Task 1.1: Data Loading and Exploration
import numpy as np
import pandas as pd

from google.colab import drive
import pandas as pd

# Mount Google Drive
drive.mount('/content/drive')

# Load CSV
file_path = '/content/drive/My Drive/DataSets/sm-datasets/StudentsPerformance.csv'

# Load the dataset
df = pd.read_csv(file_path)

# Your tasks:
# 1. Display first 10 rows
# 2. Show dataset shape and info()
# 3. Display unique values in each categorical column
# 4. Show basic statistics for all score columns

# Your code here:

Mounted at /content/drive

In [ ]:
# 1. Display first 10 rows
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [ ]:
# 2. Show dataset shape and info()
print(f"Shape of the DataSet is: {df.shape}\n")

print(df.info())

Shape of the DataSet is: (1000, 8)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None

In [ ]:
# 3. Display unique values in each categorical column
# df.apply(lambda x: x.unique())
unique_values = df.apply(lambda x: x.unique())
print(unique_values)

gender                                                            [female, male]
race/ethnicity                     [group B, group C, group A, group D, group E]
parental level of education    [bachelor's degree, some college, master's deg...
lunch                                                   [standard, free/reduced]
test preparation course                                        [none, completed]
math score                     [72, 69, 90, 47, 76, 71, 88, 40, 64, 38, 58, 6...
reading score                  [72, 90, 95, 57, 78, 83, 43, 64, 60, 54, 52, 8...
writing score                  [74, 88, 93, 44, 75, 78, 92, 39, 67, 50, 52, 4...
dtype: object

In [ ]:
# 3. Display unique values in each categorical column - alternative

for col in df.select_dtypes(include=['object', 'category']).columns:
    print(f"Unique values in '{col}': {df[col].unique()}\n")

Unique values in 'gender': ['female' 'male']

Unique values in 'race/ethnicity': ['group B' 'group C' 'group A' 'group D' 'group E']

Unique values in 'parental level of education': ["bachelor's degree" 'some college' "master's degree" "associate's degree"
 'high school' 'some high school']

Unique values in 'lunch': ['standard' 'free/reduced']

Unique values in 'test preparation course': ['none' 'completed']

In [ ]:
# 4. Show basic statistics for all score columns
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
#Task 1.2: NumPy Array Operations
# Convert score columns to numpy arrays
math_scores = df['math score'].values
reading_scores = df['reading score'].values
writing_scores = df['writing score'].values

# Your tasks:
# 1. Calculate mean, median, std, min, max for each subject using NumPy
# 2. Find total students who scored above 80 in math
# 3. Find total students who scored below 50 in any subject
# 4. Calculate the overall average score across all three subjects

# Expected output example:
# Math - Mean: 66.1, Median: 66.0, Std: 15.2
# Students with math > 80: 132
# Students with any score < 50: 178

# Your code here:

In [ ]:
# 1. Calculate mean, median, std, min, max for each subject using NumPy
# math_mean = math_scores.mean()
math_mean = np.mean(math_scores)
math_median = np.median(math_scores)
math_std = np.std(math_scores)
math_min = np.min(math_scores)
math_max = np.max(math_scores)
# print(f"Math Scores: \n 1. Mean: {math_mean:.1f}\n 2. Median: {math_median:.1f}\n 3. Std: {math_std:.1f}\n 4. Min: {math_min}\n 5. Max: {math_max}\n")
print(f"Math - Mean: {math_mean:.1f}, Median: {math_median:.1f}, Std: {math_std:.1f}, Min: {math_min}, Max: {math_max}\n")

reading_mean = np.mean(reading_scores)
reading_median = np.median(reading_scores)
reading_std = np.std(reading_scores)
reading_min = np.min(reading_scores)
reading_max = np.max(reading_scores)
# print(f"Reading Scores: \n 1. Mean: {reading_mean:.1f}\n 2. Median: {reading_median:.1f}\n 3. Std: {reading_std:.1f}\n 4. Min: {reading_min}\n 5. Max: {reading_max}\n")
print(f"Reading - Mean: {reading_mean:.1f}, Median: {reading_median:.1f}, Std: {reading_std:.1f}, Min: {reading_min}, Max: {reading_max}\n")


writing_mean = np.mean(writing_scores)
writing_median = np.median(writing_scores)
writing_std = np.std(writing_scores)
writing_min = np.min(writing_scores)
writing_max = np.max(writing_scores)
# print(f"Writing Scores: \n 1. Mean: {writing_mean:.1f}\n 2. Median: {writing_median:.1f}\n 3. Std: {writing_std:.1f}\n 4. Min: {writing_min}\n 5. Max: {writing_max}\n")
print(f"Writing - Mean: {writing_mean:.1f}, Median: {writing_median:.1f}, Std: {writing_std:.1f}, Min: {writing_min}, Max: {writing_max}\n")

Math - Mean: 66.1, Median: 66.0, Std: 15.2, Min: 0, Max: 100

Reading - Mean: 69.2, Median: 70.0, Std: 14.6, Min: 17, Max: 100

Writing - Mean: 68.1, Median: 69.0, Std: 15.2, Min: 10, Max: 100

In [ ]:
# 2. Find total students who scored above 80 in math

print(f"Students with math > 80: {np.sum(math_scores>80)}")

Students with math > 80: 176

In [ ]:
# 3. Find total students who scored below 50 in any subject
print(f"Students with < 50 in any subj: {np.sum((math_scores < 50) | (reading_scores < 50) | (writing_scores < 50))}")

Students with < 50 in any subj: 188

In [ ]:
# 4. Calculate the overall average score across all three subjects
overall_avg = (math_scores.mean() + reading_scores.mean() + writing_scores.mean()) / 3
print(f"Overall Average: {overall_avg:.1f}")

Overall Average: 67.8

In [ ]:
# Task 2.1: Identify and Handle Missing Data
# Check the dataset for any missing values
# Your tasks:
# 1. Check for null values in each column using .isnull().sum()
# 2. Check for any impossible values (scores > 100 or < 0)
# 3. Display summary of data quality

# Note: This dataset is clean, but let's verify!

# Your code here:

In [ ]:
# 1. Check for null values in each column using .isnull().sum()
print(df.isnull().sum())

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
# 2. Check for any impossible values (scores > 100 or < 0)

print(f"Impossible Values for math: {df[(df['math score']> 100) | (df['math score']< 0)]}")
print(f"Impossible Values for reading: {df[(df['reading score']> 100) | (df['reading score']< 0)]}")
print(f"Impossible Values for writing: {df[(df['writing score']> 100) | (df['writing score']< 0)]}")

Impossible Values for math: Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []
Impossible Values for reading: Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []
Impossible Values for writing: Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

In [ ]:
# 3. Display summary of data quality
missing_values = df.isnull().sum()
impossible_values_math = df[(df['math score']> 100) | (df['math score']< 0)]
impossible_values_reading = df[(df['reading score']> 100) | (df['reading score']< 0)]
impossible_values_writing = df[(df['writing score']> 100) | (df['writing score']< 0)]

if missing_values.sum() == 0 and impossible_values_math.empty and impossible_values_reading.empty and impossible_values_writing.empty:
    print("\nData quality check passed: No missing or impossible values found!")
else:
    print("\nData contains missing or impossible values!")

Data quality check passed: No missing or impossible values found!

In [ ]:
#Task 2.2: Create and Fix Missing Value
# Artificially create missing data for practice
import numpy as np

# Your tasks:
# 1. Make a copy of the dataset: df_practice = df.copy()
# 2. Randomly set 50 math scores to np.nan
# 3. Randomly set 30 writing scores to np.nan
# 4. Fill missing math scores with the MEDIAN math score
# 5. Fill missing writing scores with the MEAN writing score
# 6. Verify no missing values remain

# Steps to follow:
# Step 1: Create copy and show original missing values
df_practice = df.copy()
print("Original missing values:", df_practice.isnull().sum())

# Step 2: Create missing data
np.random.seed(42)  # For reproducible results
missing_math_idx = np.random.choice(df_practice.index, 50, replace=False)
missing_writing_idx = np.random.choice(df_practice.index, 30, replace=False)

# Continue the task...
# Your code here:

# 2. Randomly set 50 math scores to np.nan
df_practice.loc[missing_math_idx, 'math score'] = np.nan
print("\n\nAfter inserting NaN: \n")
print(df_practice[df_practice['math score'].isnull()].head(5))
# 3. Randomly set 30 writing scores to np.nan
df_practice.loc[missing_writing_idx, 'writing score'] = np.nan
print(df_practice[df_practice['writing score'].isnull()].tail(5))

Original missing values: gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64


After inserting NaN:

     gender race/ethnicity parental level of education         lunch  \
59   female        group C            some high school  free/reduced
76     male        group E            some high school      standard
96     male        group B            some high school      standard
101    male        group D           bachelor's degree      standard
136    male        group B            some high school      standard

    test preparation course  math score  reading score  writing score
59                     none         NaN             17             10
76                     none         NaN             26             22
96                completed         NaN             66             62
101               completed         NaN             74             74
136               completed         NaN             54             41
     gender race/ethnicity parental level of education         lunch  \
861  female        group E             master's degree  free/reduced
870    male        group B                 high school      standard
924    male        group D                 high school  free/reduced
967    male        group C                some college      standard
983  female        group A                some college      standard

    test preparation course  math score  reading score  writing score
861                    none        81.0             86            NaN
870                    none        59.0             58            NaN
924                    none         NaN             70            NaN
967                    none        63.0             63            NaN
983               completed        78.0             87            NaN

In [ ]:
# 4. Fill missing math scores with the MEDIAN math score
# 5. Fill missing writing scores with the MEAN writing score
# 6. Verify no missing values remain

missing_values_before_fillna = df_practice.isnull().sum()
print(missing_values_before_fillna)

import warnings

# Suppress the specific FutureWarning
warnings.simplefilter(action='ignore', category=FutureWarning)

math_median = df_practice['math score'].dropna().median()
df_practice['math score'].fillna(math_median, inplace=True)

writing_median = df_practice['writing score'].dropna().median()
df_practice['writing score'].fillna(writing_median, inplace=True)

missing_values_after_fillna = df_practice.isnull().sum()
print(missing_values_after_fillna)

gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     50
reading score                   0
writing score                  30
dtype: int64
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
#Task 3.1:Answer Simple Questions About Student Performance
# Your tasks:
# 1. Display first 5 rows using .head()
# 2. Display last 5 rows using .tail()
# 3. Show dataset shape using .shape
# 4. Show column names using .columns
# 5. Show data types using .dtypes
# 6. Show basic info using .info()

# Your code here:

In [ ]:
# 1. Display first 5 rows using .head()
df_practice.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72.0,72,74.0
1,female,group C,some college,standard,completed,69.0,90,88.0
2,female,group B,master's degree,standard,none,90.0,95,93.0
3,male,group A,associate's degree,free/reduced,none,47.0,57,44.0
4,male,group C,some college,standard,none,76.0,78,75.0

In [ ]:
# 2. Display last 5 rows using .tail()
df_practice.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88.0,99,95.0
996,male,group C,high school,free/reduced,none,62.0,55,55.0
997,female,group C,high school,free/reduced,completed,59.0,71,65.0
998,female,group D,some college,standard,completed,68.0,78,77.0
999,female,group D,some college,free/reduced,none,77.0,86,86.0

In [ ]:
# 3. Show dataset shape using .shape
df_practice.shape

(1000, 8)

In [ ]:
# 4. Show column names using .columns
print(df_practice.columns)

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [ ]:
# 5. Show data types using .dtypes
df_practice.dtypes

gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                     float64
reading score                    int64
writing score                  float64
dtype: object

In [ ]:
# 6. Show basic info using .info()
print(df_practice.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   float64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 62.6+ KB
None

In [ ]:
#Task 3.2: Basic Groupby Analysis
# Comprehensive groupby analysis
# Your tasks:

# 1. Group by 'gender' and calculate:
#    - Average scores in all subjects
#    - Count of students

# 2. Group by 'test preparation course' and show:
#    - Mean scores for each subject
#    - Show which subject benefits most from test prep

# 3. Group by 'parental level of education' and calculate:
#    - Average math score for each education level
#    - Rank education levels by math performance

# 4. Group by 'lunch' type and show:
#    - Average scores for each subject
#    - Count of students in each lunch category

# Your code here:

In [ ]:
# 1. Group by 'gender' and calculate:
#    - Average scores in all subjects
#    - Count of students
# Average scores by gender
avg_scores_by_gender = df_practice.groupby('gender')[['math score', 'reading score', 'writing score']].mean()

# Count of students by gender
count_by_gender = df_practice['gender'].value_counts()

print("Average Scores by Gender:\n", avg_scores_by_gender)
print("\nStudent Count by Gender:\n", count_by_gender)

Average Scores by Gender:
         math score  reading score  writing score
gender
female   64.247104      72.608108      72.088803
male     68.412863      65.473029      63.483402

Student Count by Gender:
 gender
female    518
male      482
Name: count, dtype: int64

In [ ]:
# avg_scores_by_gender

In [ ]:
# Mean scores by test preparation course
avg_scores_by_prep = df_practice.groupby('test preparation course')[['math score', 'reading score', 'writing score']].mean()
avg_scores_by_prep

                         math score  reading score  writing score
test preparation course
completed                 69.734637      73.893855      74.100559
none                      64.314642      66.534268      64.506231

In [ ]:

# 2. Group by 'test preparation course' and show:
#    - Mean scores for each subject
#    - Show which subject benefits most from test prep

# Calculate improvement due to test preparation
prep_effect = avg_scores_by_prep.loc['completed'] - avg_scores_by_prep.loc['none']
most_improved_subject = prep_effect.idxmax()
prep_effect

math score       5.419995
reading score    7.359587
writing score    9.594328
dtype: float64

In [ ]:
most_improved_subject

'writing score'

In [ ]:

print("Average Scores by Test Preparation Course:\n", avg_scores_by_prep)
print("\nScore Improvement from Test Prep:\n", prep_effect)
print(f"\nSubject that benefits most from test prep: {most_improved_subject}")

Average Scores by Test Preparation Course:
                          math score  reading score  writing score
test preparation course
completed                 69.734637      73.893855      74.100559
none                      64.314642      66.534268      64.506231

Score Improvement from Test Prep:
 math score       5.419995
reading score    7.359587
writing score    9.594328
dtype: float64

 Subject that benefits most from test prep: writing score

In [ ]:
# 3. Group by 'parental level of education' and calculate:
#    - Average math score for each education level
#    - Rank education levels by math performance

# Average math score by parental education
math_by_education = df_practice.groupby('parental level of education')['math score'].mean()

# Rank education levels by math performance (descending)
ranked_math_by_education = math_by_education.sort_values(ascending=False)

print("Average Math Score by Parental Level of Education:\n", math_by_education)
print("\nRanked Education Levels by Math Score:\n", ranked_math_by_education)

Average Math Score by Parental Level of Education:
 parental level of education
associate's degree    67.463964
bachelor's degree     69.567797
high school           62.760204
master's degree       69.406780
some college          67.234513
some high school      64.122905
Name: math score, dtype: float64

Ranked Education Levels by Math Score:
 parental level of education
bachelor's degree     69.567797
master's degree       69.406780
associate's degree    67.463964
some college          67.234513
some high school      64.122905
high school           62.760204
Name: math score, dtype: float64

In [ ]:
# 4. Group by 'lunch' type and show:
#    - Average scores for each subject
#    - Count of students in each lunch category

avg_score_by_lunch = df_practice.groupby('lunch')[['math score', 'reading score', 'writing score']].mean()
# avg_score_by_lunch
count_by_lunch = df_practice['lunch'].value_counts()

print(f"Average score by lunch type: {avg_score_by_lunch}\n")
print(f"Student Count by lunch type: {count_by_lunch}\n")

Average score by lunch type:               math score  reading score  writing score
lunch
free/reduced   59.430986      64.653521      63.045070
standard       70.010853      71.654264      70.635659

Student Count by lunch type: lunch
standard        645
free/reduced    355
Name: count, dtype: int64

In [ ]:
#Task 3.3: Use your data analysis skills to answer these easy questions:

# 1. Who performs better in math - males or females?
#    - Calculate average math score by gender
#    - Show the difference between male and female average

# 2. Which subject do students perform best in overall?
#    - Calculate the overall average for math, reading, and writing
#    - Rank the subjects from highest to lowest average score

# 3. What's the impact of parental education?
#    - Find the average total score for each parental education level
#    - Identify which education level leads to highest student performance

In [ ]:
# Average math score by gender
avg_math_by_gender = df_practice.groupby('gender')['math score'].mean()

# Difference between female and male average
math_diff = avg_math_by_gender['female'] - avg_math_by_gender['male']

print("Average Math Score by Gender:")
print(avg_math_by_gender)
print(f"\n Difference (Female - Male): {math_diff:.2f}")

# Who performs better?
better_math_gender = 'Female' if math_diff > 0 else 'Male'
print(f"\n {better_math_gender} students perform better in math.")

Average Math Score by Gender:
gender
female    64.247104
male      68.412863
Name: math score, dtype: float64

 Difference (Female - Male): -4.17

 Male students perform better in math.

In [ ]:
# Calculate average scores for each subject
subject_averages = df_practice[['math score', 'reading score', 'writing score']].mean()

# Sort from highest to lowest
ranked_subjects = subject_averages.sort_values(ascending=False)

print("Average Scores by Subject:")
print(subject_averages)
print("\n Subjects Ranked by Performance:")
print(ranked_subjects)

# Best performing subject
top_subject = ranked_subjects.idxmax()
print(f"\n Students perform best in: {top_subject}")

Average Scores by Subject:
math score       66.255
reading score    69.169
writing score    67.941
dtype: float64

 Subjects Ranked by Performance:
reading score    69.169
writing score    67.941
math score       66.255
dtype: float64

 Students perform best in: reading score

In [ ]:
# Add total score column
df_practice['total score'] = df_practice['math score'] + df_practice['reading score'] + df_practice['writing score']

# Average total score by parental education
avg_total_by_education = df_practice.groupby('parental level of education')['total score'].mean()

# Rank education levels by total score
ranked_education = avg_total_by_education.sort_values(ascending=False)

print("Average Total Score by Parental Education Level:")
print(avg_total_by_education)
print("\n Education Levels Ranked by Student Performance:")
print(ranked_education)

# Best-performing education level
top_education = ranked_education.idxmax()
print(f"\n Highest student performance is seen when parents have: {top_education}")

Average Total Score by Parental Education Level:
parental level of education
associate's degree    208.229730
bachelor's degree     215.059322
high school           190.091837
master's degree       219.661017
some college          205.526549
some high school      196.055866
Name: total score, dtype: float64

 Education Levels Ranked by Student Performance:
parental level of education
master's degree       219.661017
bachelor's degree     215.059322
associate's degree    208.229730
some college          205.526549
some high school      196.055866
high school           190.091837
Name: total score, dtype: float64

 Highest student performance is seen when parents have: master's degree